version: '3.1'
services:
  postgresql:    
    image: postgres
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb
    volumes:
      - ./database:/docker-entrypoint-initdb.d/  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
